import './globals.css'
import { Header } from '@/widgets/Header'
import { SecondHeader } from '@/widgets/SecondHeader'
import { Footer } from '@/widgets/Footer'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AppProvider from './_utils/AppProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<body className={inter.className}>
				<AppProvider>
					<Header/>
					<SecondHeader/>
					{children}
					<Footer/>
				</AppProvider>
			</body>
		</html>
	)
}
